# fly.toml app configuration file generated for leaderboardapp on 2023-09-05T06:38:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leaderboardapp"
primary_region = "sea"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.0"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  DB_DATABASE = "some_db"
  DB_HOST = "sea.leaderboarddb.internal"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
